apiVersion: v1
kind: Pod
metadata:
  name: gcloud-debug
  labels:
    app: gcloud
spec:
  containers:
  - name: gcloud-sdk
    image: google/cloud-sdk:433.0.1-debian_component_based
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
  restartPolicy: Always
